obstacle_range: 2.5   #2.5
raytrace_range: 3.0   #3.0
footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#footprint_inflation: 0.01
# robot_radius: 0.175  #0.175
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan #观察数据来源
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

# if set to false,then obstacle layer take unknow space to be free.
obstacle_layer:
   track_unknown_space: true
